Repository lblod/ember-rdfa-editor-article-structure-plugin, pull requests merged in 2022-10, with the labels that each got.

#7 Bugfix/dont fail on empty selection
  addon/components/article-card.js
  addon/components/article-structure-card.js
  addon/components/paragraph-card.js
  addon/components/structure-card.js
Labels: bug

#8 chore(dx): setup addon to hot-reload when in dev mode
  index.js
Labels: internal

#9 Add release-it packages and release script
  .release-it.json
  package-lock.json
  package.json
Labels: internal

#10 Update node to 16.17.1 (latest lts)
  package-lock.json
  package.json
Labels: internal

#12 Add the name of the structure to the placeholder of the title
  addon/commands/insert-article-structure-command.js
  addon/components/article-structure-card.js
  addon/utils/constants.js
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#14 Order the structures hierarchically
  addon/components/article-structure-card.hbs
Labels: enhancement
